# Generated by Django 4.2.29 on 2026-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_school_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_totp_secret',
            field=models.CharField(blank=True, default='', help_text='Base32 TOTP secret (empty until the user enrolls in MFA).', max_length=64),
        ),
    ]
