# Generated by Django 4.2.29 on 2026-08-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_mfa_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner (Platform Level)'), ('SUPER_ADMIN', 'Super Admin (Organization / Tenant)'), ('ZONAL_ADMIN', 'Zonal Admin'), ('CHIEF_ACCOUNTANT', 'Chief Accountant'), ('PRINCIPAL', 'Principal'), ('BRANCH_ADMIN', 'Branch Admin (School Level)'), ('ACCOUNTANT', 'Accountant'), ('TEACHER', 'Teacher'), ('ATTENDANCE_DEVICE', 'Attendance Device'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], max_length=30),
        ),
    ]
