# Generated by Django 4.2.29 on 2026-07-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_branch_admission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='staff_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
