# Generated by Django 4.2.29 on 2026-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_initial_payment_markers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_APPROVAL', 'Pending Approval'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred'), ('GRADUATED', 'Graduated'), ('DETAINED', 'Detained'), ('DROPOUT', 'Dropout'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
