# Generated by Django 4.2.29 on 2026-05-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimportjob',
            name='update_fee_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvimportjob',
            name='update_student_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvimportjob',
            name='updated_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
