# Generated by Django 4.2.29 on 2026-07-08 17:06

from django.db import migrations
from django.db.models import Subquery, OuterRef

def copy_grades(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    StudentAcademicRecord = apps.get_model('students', 'StudentAcademicRecord')
    ClassSection = apps.get_model('students', 'ClassSection')

    class_section_subquery = ClassSection.objects.filter(id=OuterRef('class_section_id')).values('grade')[:1]
    
    Student.objects.filter(class_section__isnull=False).update(
        grade=Subquery(class_section_subquery)
    )
    
    StudentAcademicRecord.objects.filter(class_section__isnull=False).update(
        grade=Subquery(class_section_subquery)
    )

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_student_grade_studentacademicrecord_grade'),
    ]

    operations = [
        migrations.RunPython(copy_grades, reverse_code=migrations.RunPython.noop),
    ]
