# Generated by Django 4.2.29 on 2026-07-08 17:10

from django.db import migrations

def backfill_nulls(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    StudentAcademicRecord = apps.get_model('students', 'StudentAcademicRecord')
    
    Student.objects.filter(grade__isnull=True).update(grade='NURSERY')
    StudentAcademicRecord.objects.filter(grade__isnull=True).update(grade='NURSERY')

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_backfill_student_grade'),
    ]

    operations = [
        migrations.RunPython(backfill_nulls, reverse_code=migrations.RunPython.noop),
    ]
