# Generated by Django 4.2.29 on 2026-07-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_backfill_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('NURSERY', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11_SCIENCE', 'Grade 11 Science'), ('11_COMMERCE', 'Grade 11 Commerce'), ('11_ARTS', 'Grade 11 Arts'), ('12_SCIENCE', 'Grade 12 Science'), ('12_COMMERCE', 'Grade 12 Commerce'), ('12_ARTS', 'Grade 12 Arts')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentacademicrecord',
            name='grade',
            field=models.CharField(choices=[('NURSERY', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11_SCIENCE', 'Grade 11 Science'), ('11_COMMERCE', 'Grade 11 Commerce'), ('11_ARTS', 'Grade 11 Arts'), ('12_SCIENCE', 'Grade 12 Science'), ('12_COMMERCE', 'Grade 12 Commerce'), ('12_ARTS', 'Grade 12 Arts')], db_index=True, max_length=50),
        ),
    ]
