# Generated by Django 4.2.29 on 2026-07-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='needs_fee_setup',
            field=models.BooleanField(default=False),
        ),
    ]
