# Generated by Django 4.2.29 on 2026-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_student_needs_fee_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='books_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='books_status',
            field=models.CharField(choices=[('NOT_TAKEN', 'Not Taken'), ('TAKEN', 'Taken')], default='NOT_TAKEN', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='government_assigned_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
