import React, { useState, useEffect } from 'react';
import { X, Code, Palette, Play } from 'lucide-react';
import api from '@/lib/axios';

export interface DocumentTemplate {
  id?: string;
  name: string;
  type:
    | 'ID_CARD'
    | 'FEE_RECEIPT'
    | 'TRANSPORT_FEE_RECEIPT'
    | 'TRANSFER_CERTIFICATE'
    | 'HALL_TICKET'
    | 'REPORT_CARD'
    | 'REPORT_CARD_SUMMARY'
    | 'VENDOR_BILL_RECEIPT';
  mode: 'CONFIG' | 'HTML';
  config_data: {
    background_color?: string;
    text_color?: string;
    primary_color?: string;
    school_name?: string;
    [key: string]: any;
  };
  raw_html: string;
  is_active: boolean;
  is_default: boolean;
  updated_at?: string;
}

interface TemplateEditorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSaved: () => void;
  template?: DocumentTemplate | null;
}

const TEMPLATE_TYPES = [
  { value: 'ID_CARD', label: 'ID Card' },
  { value: 'FEE_RECEIPT', label: 'Fee Receipt' },
  { value: 'TRANSPORT_FEE_RECEIPT', label: 'Transport Fee Receipt' },
  { value: 'TRANSFER_CERTIFICATE', label: 'Transfer Certificate' },
  { value: 'HALL_TICKET', label: 'Hall Ticket' },
  { value: 'REPORT_CARD', label: 'Report Card (per student)' },
  { value: 'REPORT_CARD_SUMMARY', label: 'Report Card Summary (section)' },
  { value: 'VENDOR_BILL_RECEIPT', label: 'Vendor Bill Receipt' },
];

export default function TemplateEditorModal({ isOpen, onClose, onSaved, template }: TemplateEditorModalProps) {
  const [formData, setFormData] = useState<DocumentTemplate>({
    name: '',
    type: 'ID_CARD',
    mode: 'CONFIG',
    config_data: { background_color: '#ffffff', text_color: '#000000', school_name: '' },
    raw_html: '',
    is_active: true,
    is_default: false,
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (isOpen) {
      if (template) {
        setFormData({
          ...template,
          config_data: template.config_data || { background_color: '#ffffff', text_color: '#000000', school_name: '' }
        });
      } else {
        setFormData({
          name: '',
          type: 'ID_CARD',
          mode: 'CONFIG',
          config_data: { background_color: '#ffffff', text_color: '#000000', school_name: '' },
          raw_html: '',
          is_active: true,
          is_default: false,
        });
      }
      setError('');
    }
  }, [isOpen, template]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      if (formData.id) {
        await api.put(`templates/${formData.id}/`, formData);
      } else {
        await api.post('templates/', formData);
      }
      onSaved();
      onClose();
    } catch (err: any) {
      setError(err.response?.data?.error || err.response?.data?.detail || 'Failed to save template. Please check for raw_html errors if in HTML mode.');
    } finally {
      setLoading(false);
    }
  };

  const handleConfigChange = (field: string, value: string) => {
    setFormData((prev) => ({
      ...prev,
      config_data: {
        ...prev.config_data,
        [field]: value
      }
    }));
  };

  const handlePreview = async () => {
    try {
      setLoading(true);
      setError('');
      const response = await api.post('templates/preview/', formData, {
        responseType: 'blob' // Important to handle PDF binary stream
      });
      
      const fileURL = URL.createObjectURL(new Blob([response.data], { type: 'application/pdf' }));
      const newWindow = window.open(fileURL, '_blank');
      if (!newWindow) {
        setError("Pop-up blocked. Please allow pop-ups for this site to preview the PDF.");
      }
    } catch (err: any) {
      if (err.response && err.response.data instanceof Blob) {
        // Because responseType is 'blob', we have to read it back to text to get the JSON error
        const text = await err.response.data.text();
        try {
          const json = JSON.parse(text);
          setError(json.error || 'Preview failed to generate on the server.');
        } catch (e) {
          setError('Preview failed: Internal Server Error.');
        }
      } else {
        setError(err.response?.data?.error || 'Preview failed: Check your raw HTML for syntax errors.');
      }
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col shadow-2xl">
        {/* Header */}
        <div className="p-6 border-b border-gray-100 flex items-center justify-between bg-gray-50/50">
          <div>
            <h2 className="text-xl font-bold text-gray-900">{template ? 'Edit Template' : 'New Template'}</h2>
            <p className="text-sm text-gray-500 mt-1">Design how documents look when generated by the ERP.</p>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-gray-200 rounded-full transition-colors text-gray-500">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto flex-1">
          {error && (
            <div className="mb-6 p-4 bg-red-50 text-red-600 rounded-xl text-sm border border-red-100">
              {error}
            </div>
          )}

          <form id="template-form" onSubmit={handleSubmit} className="space-y-6">
            
            {/* Basic Info */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-6 bg-gray-50 rounded-xl border border-gray-100">
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">Template Name</label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder="e.g. Standard Winter ID Card"
                  className="w-full p-3 bg-white border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                  required
                />
              </div>
              
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">Document Type</label>
                <select
                  value={formData.type}
                  onChange={(e) => setFormData({ ...formData, type: e.target.value as any })}
                  className="w-full p-3 bg-white border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                  required
                >
                  {TEMPLATE_TYPES.map((t) => (
                    <option key={t.value} value={t.value}>{t.label}</option>
                  ))}
                </select>
              </div>

              <div className="flex items-center space-x-3 bg-white p-3 rounded-xl border border-gray-200 col-span-full">
                <input
                  type="checkbox"
                  id="is_default"
                  checked={formData.is_default}
                  onChange={(e) => setFormData({ ...formData, is_default: e.target.checked })}
                  className="w-5 h-5 text-blue-600 rounded"
                />
                <label htmlFor="is_default" className="text-sm font-medium text-gray-700 cursor-pointer">
                  Set as Default Active Template for this Type
                </label>
              </div>
            </div>

            {/* Editing Mode Selection */}
            <div className="border-t border-gray-100 pt-6">
              <label className="block text-sm font-semibold text-gray-700 mb-4">Editing Mode</label>
              <div className="grid grid-cols-2 gap-4">
                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, mode: 'CONFIG' })}
                  className={`flex flex-col items-center justify-center p-6 border-2 rounded-xl transition-all ${
                    formData.mode === 'CONFIG' ? 'border-blue-600 bg-blue-50 text-blue-700' : 'border-gray-200 hover:border-blue-300 text-gray-600'
                  }`}
                >
                  <Palette className="w-8 h-8 mb-2" />
                  <span className="font-semibold">Standard Configuration</span>
                  <span className="text-xs mt-1 text-center opacity-80">Safe, easy to use UI fields to select colors and properties.</span>
                </button>
                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, mode: 'HTML' })}
                  className={`flex flex-col items-center justify-center p-6 border-2 rounded-xl transition-all ${
                    formData.mode === 'HTML' ? 'border-purple-600 bg-purple-50 text-purple-700' : 'border-gray-200 hover:border-purple-300 text-gray-600'
                  }`}
                >
                  <Code className="w-8 h-8 mb-2" />
                  <span className="font-semibold">Raw HTML/CSS</span>
                  <span className="text-xs mt-1 text-center opacity-80">Advanced. Write your own Django template code.</span>
                </button>
              </div>
            </div>

            {/* Mode Content Editor */}
            <div className="mt-6">
              {formData.mode === 'CONFIG' ? (
                 <div className="space-y-6">
                   <div className="grid grid-cols-1 md:grid-cols-2 gap-6 bg-gradient-to-br from-blue-50/50 to-transparent p-6 rounded-xl border border-blue-100">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">School Label Overlay (Optional)</label>
                      <input
                        type="text"
                        value={formData.config_data.school_name || ''}
                        onChange={(e) => handleConfigChange('school_name', e.target.value)}
                        placeholder="Overwrites default school name"
                        className="w-full p-3 bg-white border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
                      />
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">Background Color</label>
                        <div className="flex space-x-2">
                          <input
                            type="color"
                            value={formData.config_data.background_color || '#ffffff'}
                            onChange={(e) => handleConfigChange('background_color', e.target.value)}
                            className="w-12 h-12 p-1 bg-white border border-gray-200 rounded-lg cursor-pointer"
                          />
                          <input type="text" value={formData.config_data.background_color} readOnly className="w-full px-3 text-sm bg-gray-50 border border-gray-200 rounded-lg" />
                        </div>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">Text Color</label>
                        <div className="flex space-x-2">
                          <input
                            type="color"
                            value={formData.config_data.text_color || '#000000'}
                            onChange={(e) => handleConfigChange('text_color', e.target.value)}
                            className="w-12 h-12 p-1 bg-white border border-gray-200 rounded-lg cursor-pointer"
                          />
                          <input type="text" value={formData.config_data.text_color} readOnly className="w-full px-3 text-sm bg-gray-50 border border-gray-200 rounded-lg" />
                        </div>
                      </div>
                    </div>
                   </div>
                 </div>
              ) : (
                <div className="space-y-4">
                  <div className="bg-purple-50 p-4 rounded-lg flex items-start space-x-3">
                    <Code className="w-5 h-5 text-purple-600 mt-0.5" />
                    <div>
                      <h4 className="text-sm font-semibold text-purple-900">Variables you can use:</h4>
                      <p className="text-xs text-purple-700 mt-1 space-y-1">
                        Django template syntax, e.g. <code>{`{{ student.first_name }}`}</code>.
                        Context keys by type: <code>tenant_name</code>, <code>tenant_logo</code>, <code>branch_name</code>;
                        <code>student</code> (ID card, hall ticket, report card);
                        <code>exam</code> (name, start_date, end_date, academic_year) for hall ticket &amp; report card;
                        <code>subjects</code> and <code>aggregate</code> for report card;
                        <code>students</code> (list of rows with <code>student</code>, <code>aggregate</code>) for report card summary;
                        <code>payment</code> / <code>invoice</code> for fee receipts;
                        <code>tc</code> (certificate fields) plus <code>student.father_name</code> / <code>mother_name</code> for transfer certificates;
                        <strong>Vendor Bill:</strong> <code>vendor.name</code>, <code>bill.bill_id</code>, <code>bill.voucher_number</code>, <code>bill.bill_date</code>, <code>bill.payment_mode</code>, <code>bill.status</code>, <code>bill.total_amount</code>, <code>bill.tds_amount</code>, <code>bill.net_amount</code>, <code>bill.description</code>, <code>bill.items</code> (list with <code>expense_type_name</code>, <code>amount</code>), <code>amount_in_words</code>, <code>processed_by</code>.
                      </p>
                    </div>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">HTML Source Code</label>
                    <textarea
                      value={formData.raw_html || ''}
                      onChange={(e) => setFormData({ ...formData, raw_html: e.target.value })}
                      rows={12}
                      placeholder="<html><body><h1>Receipt {{ payment.receipt_number }}</h1></body></html>"
                      className="w-full p-4 font-mono text-sm bg-gray-900 text-green-400 border border-gray-800 rounded-xl focus:ring-2 focus:ring-purple-500 outline-none"
                    ></textarea>
                  </div>
                </div>
              )}
            </div>
            
          </form>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-gray-100 bg-gray-50 flex justify-between space-x-4">
          <div className="flex space-x-3">
             <button
               type="button"
               onClick={handlePreview}
               disabled={loading}
               className="px-5 py-2.5 bg-gray-800 hover:bg-gray-900 text-white font-medium rounded-xl transition-all flex items-center"
             >
               <Play className="w-4 h-4 mr-2" />
               Preview PDF Layer
             </button>
          </div>
          <div className="flex space-x-3">
            <button
              type="button"
              onClick={onClose}
              className="px-6 py-2.5 text-gray-700 font-medium hover:bg-gray-200 rounded-xl transition-colors"
            >
              Cancel
            </button>
            <button
              form="template-form"
              type="submit"
              disabled={loading}
              className="px-8 py-2.5 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-xl shadow-lg shadow-blue-200 transition-all flex items-center"
            >
              {loading ? 'Saving...' : 'Save Template'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
