# Generated by Django 4.2.29 on 2026-08-14 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0013_fix_employee_id_format'),
        ('tenants', '0010_add_branch_staff_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendanceTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, help_text='Random hex token encoded in the QR code', max_length=64, unique=True)),
                ('token_hmac', models.CharField(help_text='HMAC-SHA256 of the token for integrity verification', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('EXPIRED', 'Expired'), ('USED', 'Used')], default='PENDING', max_length=10)),
                ('expires_at', models.DateTimeField(help_text='Token expiry time (15 seconds from creation)')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_transactions', to='tenants.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_transactions', to='staff.staffprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance_transactions', to='tenants.tenant')),
                ('user', models.ForeignKey(help_text='The user who generated the QR code', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_transactions', to=settings.AUTH_USER_MODEL)),
                ('validated_by_device', models.ForeignKey(blank=True, help_text='The ATTENDANCE_DEVICE user that scanned the QR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_attendance_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Attendance date')),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_photo', models.CharField(blank=True, default='', help_text='S3 key for check-in photo', max_length=500)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_photo', models.CharField(blank=True, default='', help_text='S3 key for check-out photo', max_length=500)),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('ON_LEAVE', 'On Leave'), ('ABSENT', 'Absent')], default='ABSENT', max_length=15)),
                ('source', models.CharField(choices=[('QR_DEVICE', 'QR Device Scan'), ('MANUAL_ADMIN', 'Manual Admin Entry'), ('SYSTEM', 'System Generated')], default='QR_DEVICE', max_length=15)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to='tenants.branch')),
                ('check_in_device', models.ForeignKey(blank=True, help_text='The ATTENDANCE_DEVICE user that recorded check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_checkins_recorded', to=settings.AUTH_USER_MODEL)),
                ('check_in_transaction', models.ForeignKey(blank=True, help_text='The QR transaction used for check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_attendance', to='staff_attendance.staffattendancetransaction')),
                ('check_out_device', models.ForeignKey(blank=True, help_text='The ATTENDANCE_DEVICE user that recorded check-out', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_checkouts_recorded', to=settings.AUTH_USER_MODEL)),
                ('check_out_transaction', models.ForeignKey(blank=True, help_text='The QR transaction used for check-out', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_out_attendance', to='staff_attendance.staffattendancetransaction')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to='staff.staffprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date', 'staff__user__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='staffattendancetransaction',
            index=models.Index(fields=['token', 'status'], name='staff_atten_token_d11b03_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendancetransaction',
            index=models.Index(fields=['staff', 'status'], name='staff_atten_staff_i_3cedf2_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendancetransaction',
            index=models.Index(fields=['expires_at'], name='staff_atten_expires_1cb7bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffattendancetransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('staff',), name='unique_pending_token_per_staff'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['staff', 'date'], name='staff_atten_staff_i_9d1cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['branch', 'date'], name='staff_atten_branch__bca34a_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['tenant', 'date', 'status'], name='staff_atten_tenant__b16881_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.UniqueConstraint(fields=('staff', 'date'), name='unique_staff_attendance_per_day'),
        ),
    ]
