# Generated by Django 4.2.29 on 2026-08-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffattendance',
            options={'ordering': ['-date', '-created_at']},
        ),
    ]
