# Generated by Django 4.2.29 on 2026-07-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_examresult_subject_and_more'),
        ('homework', '0002_homeworkacknowledgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='academics.academicsubject'),
        ),
    ]
