# Generated by Django 4.2.29 on 2026-06-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_examresult_is_published_examresult_subject_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
