# Generated by Django 4.2.29 on 2026-06-01 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_csvimportjob_update_fee_details_and_more'),
        ('tenants', '0009_branch_admission_fee'),
        ('timetable', '0003_alter_classsubjectdemand_unique_together'),
        ('academics', '0003_examresult_is_absent_alter_examresult_marks_obtained'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubjectConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_configs', to='tenants.branch')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_configs', to='students.classsection')),
                ('exam_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='academics.examterm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_configs', to='timetable.subject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_configs', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('exam_term', 'class_section', 'subject')},
            },
        ),
    ]
