# Generated by Django 4.2.29 on 2026-07-10 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_alter_student_grade_and_more'),
        ('tenants', '0009_branch_admission_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0004_examsubjectconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('is_optional', models.BooleanField(default=False, help_text='If True, subject appears in the Optional Subjects section of assessments.')),
                ('is_first_language', models.BooleanField(default=False)),
                ('is_second_language', models.BooleanField(default=False)),
                ('is_third_language', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_subjects', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_subjects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='tenants.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='tenants.branch')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.classsection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['start_date'],
                'unique_together': {('branch', 'academic_year', 'class_section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.TimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_subjects', to='academics.assessment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_subjects', to='academics.academicsubject')),
            ],
            options={
                'ordering': ['subject__display_order', 'subject__name'],
                'unique_together': {('assessment', 'subject')},
            },
        ),
    ]
