# Generated by Django 4.2.29 on 2026-07-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_assessment_unique_together_assessment_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.academicsubject'),
        ),
        migrations.AlterField(
            model_name='examsubjectconfig',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_configs', to='academics.academicsubject'),
        ),
    ]
