# Generated by Django 4.2.29 on 2026-07-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_student_needs_fee_setup'),
        ('academics', '0008_populate_academic_subjects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examterm',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='examterm',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='examterm',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='examterm',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examresult',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.assessment'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'assessment', 'subject')},
        ),
        migrations.DeleteModel(
            name='ExamSubjectConfig',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='exam_term',
        ),
        migrations.DeleteModel(
            name='ExamTerm',
        ),
    ]
