# Generated by Django 4.2.29 on 2026-07-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_examterm_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='assessment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.assessment'),
            preserve_default=False,
        ),
    ]
