# Generated by Django 4.2.29 on 2026-07-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_examresult_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked')], db_index=True, default='DRAFT', help_text='DRAFT=configuring, ACTIVE=marks entry open, LOCKED=published/immutable', max_length=10),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_results', to='academics.academicsubject'),
        ),
    ]
