# Generated by Django

from django.db import migrations

def seed_grade_scale(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    Branch = apps.get_model('tenants', 'Branch')
    GradeScale = apps.get_model('academics', 'GradeScale')

    scales = [
        ('A1', 91.0, 100.0, 10.0, 'Outstanding'),
        ('A2', 81.0, 90.99, 9.0, 'Excellent'),
        ('B1', 71.0, 80.99, 8.0, 'Very Good'),
        ('B2', 61.0, 70.99, 7.0, 'Good'),
        ('C1', 51.0, 60.99, 6.0, 'Above Average'),
        ('C2', 41.0, 50.99, 5.0, 'Satisfactory'),
        ('D1', 33.0, 40.99, 4.0, 'Needs Improvement'),
        ('D2', 21.0, 32.99, 0.0, 'Requires Significant Improvement'),
        ('E', 0.0, 20.99, 0.0, 'Unsatisfactory / Improvement Required'),
    ]

    # We will seed this for all branches that exist
    for branch in Branch.objects.all():
        # Clean existing 'Standard Indian Scale' to avoid duplicates
        GradeScale.objects.filter(branch=branch, name='Standard Indian Scale').delete()
        
        for grade, min_p, max_p, point, remark in scales:
            GradeScale.objects.create(
                tenant=branch.tenant,
                branch=branch,
                name='Standard Indian Scale',
                grade=grade,
                min_marks_percent=min_p,
                max_marks_percent=max_p,
                grade_point=point,
                remarks=remark
            )

    # Recalculate grades for all existing ExamResult records
    ExamResult = apps.get_model('academics', 'ExamResult')
    for result in ExamResult.objects.exclude(marks_obtained__isnull=True):
        if result.max_marks > 0:
            percentage = (result.marks_obtained / result.max_marks) * 100
            scale = GradeScale.objects.filter(
                branch_id=result.branch_id,
                min_marks_percent__lte=percentage,
                max_marks_percent__gte=percentage
            ).first()
            if scale:
                result.grade = scale.grade
                result.grade_point = scale.grade_point
                result.save(update_fields=['grade', 'grade_point'])

def reverse_seed_grade_scale(apps, schema_editor):
    GradeScale = apps.get_model('academics', 'GradeScale')
    GradeScale.objects.filter(name='Standard Indian Scale').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_assessment_status_and_examresult_protect'),
        ('tenants', '0001_initial'), # Ensure tenants app is loaded
    ]

    operations = [
        migrations.RunPython(seed_grade_scale, reverse_seed_grade_scale),
    ]
