# Generated by Django 4.2.29 on 2026-07-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_populate_academic_subjects'),
        ('timetable', '0003_alter_classsubjectdemand_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubjectdemand',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='academics.academicsubject'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='academics.academicsubject'),
        ),
    ]
