# Generated by Django 4.2.29 on 2026-07-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_teacherassignment_subject'),
        ('timetable', '0004_alter_classsubjectdemand_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubjectdemand',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_demands', to='staff.staffprofile'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='staff.staffprofile'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
