import uuid
from django.db import models
from django.conf import settings


class SalaryStatement(models.Model):
    """
    Monthly salary statement for a staff member.
    One record per staff per month+year. Generated by admin,
    stores computed attendance summary and salary calculation.
    """
    STATUS_CHOICES = [
        ('DRAFT', 'Draft'),
        ('FINALIZED', 'Finalized'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tenant = models.ForeignKey('tenants.Tenant', on_delete=models.CASCADE, related_name='salary_statements')
    branch = models.ForeignKey('tenants.Branch', on_delete=models.CASCADE, related_name='salary_statements')
    staff = models.ForeignKey('staff.StaffProfile', on_delete=models.CASCADE, related_name='salary_statements')

    month = models.PositiveSmallIntegerField()  # 1-12
    year = models.PositiveIntegerField()

    # Attendance summary (computed at generation time)
    total_working_days = models.PositiveIntegerField(default=0)
    present_days = models.PositiveIntegerField(default=0)
    absent_days = models.PositiveIntegerField(default=0)
    late_in_count = models.PositiveIntegerField(default=0)
    early_out_count = models.PositiveIntegerField(default=0)
    leave_days = models.PositiveIntegerField(default=0)
    half_days = models.PositiveIntegerField(default=0)

    # Salary
    gross_salary = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    manual_deduction = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    deduction_reason = models.TextField(blank=True, default='')
    net_salary = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='DRAFT')
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='generated_salary_statements'
    )
    generated_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-year', '-month', 'staff__employee_id']
        constraints = [
            models.UniqueConstraint(
                fields=['staff', 'month', 'year'],
                name='unique_salary_statement_per_staff_month'
            )
        ]
        indexes = [
            models.Index(fields=['branch', 'year', 'month']),
            models.Index(fields=['tenant', 'year', 'month']),
        ]

    def __str__(self):
        return f"{self.staff} - {self.year}/{self.month:02d} - {self.status}"
