# Generated by Django 4.2.29 on 2026-06-10 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0009_branch_admission_fee'),
        ('students', '0018_csvimportjob_update_fee_details_and_more'),
        ('transport', '0002_remove_studenttransport_route_delete_transportroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportFeeEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_point', models.CharField(blank=True, max_length=200)),
                ('agreed_amount', models.DecimalField(decimal_places=2, help_text='Annual transport fee agreed for this student', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fee_enrollments', to='tenants.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fee_enrollments', to='tenants.branch')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_fee_enrollments_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fee_enrollments', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fee_enrollments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
