# Generated by Django 4.2.29 on 2026-06-11 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0009_branch_admission_fee'),
        ('expenses', '0003_alter_expense_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_id', models.CharField(max_length=50, unique=True)),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tds_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('bill_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendor_bills', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bills', to='tenants.branch')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_vendor_bills', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bills', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='associated_expense_types',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], default='COMPANY', max_length=20),
        ),
        migrations.CreateModel(
            name='VendorBillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.vendorbill')),
                ('expense_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bill_items', to='expenses.expensecategory')),
            ],
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='expenses.vendor'),
        ),
    ]
