# Generated by Django 4.2.29 on 2026-06-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_vendorbill_vendor_aadhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('COMMUTE', 'Commute')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('COMMUTE', 'Commute')], default='GENERAL', max_length=20),
        ),
    ]
