# Generated by Django 4.2.29 on 2026-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_feestructureitem_locked_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeapprovalrequest',
            name='routing',
            field=models.CharField(choices=[('ZONAL', 'Zonal admin'), ('TENANT_SUPER', 'Tenant super admin')], default='TENANT_SUPER', max_length=20),
        ),
    ]
