# Generated by Django 4.2.29 on 2026-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0012_alter_feeapprovalrequest_routing'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeapprovalrequest',
            name='request_type',
            field=models.CharField(choices=[('ADMISSION', 'Admission'), ('CONCESSION', 'Concession')], default='ADMISSION', help_text='ADMISSION = enrollment-time discount; CONCESSION = post-enrollment request from student profile', max_length=15),
        ),
    ]
