# Generated by Django 4.2.29 on 2026-07-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_teacherprofile_branch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherProfile',
            new_name='StaffProfile',
        ),
        migrations.RenameField(
            model_name='teacherassignment',
            old_name='teacher',
            new_name='staff',
        ),
    ]
