# Generated by Django 4.2.29 on 2026-07-16 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0009_branch_admission_fee'),
        ('staff', '0003_rename_teacher_to_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employment_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract')], default='PERMANENT', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='experience_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pf_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='uan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='tenants.branch'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StaffIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id_counter', to='tenants.branch')),
            ],
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_teaching_role', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_categories', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_categories', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='tenants.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='staff.staffcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staff.staffcategory'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staff.department'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staff.designation'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='qualification_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staff.qualification'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='specialization_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staff.specialization'),
        ),
    ]
