# Generated by Django 4.2.29 on 2026-07-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_phase6_add_missing_hr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employment_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary')], default='REGULAR', max_length=20),
        ),
    ]
