# Generated by Django 4.2.29 on 2026-07-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_add_personal_email_update_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
