# Generated by Django 4.2.29 on 2026-07-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_classsubjectdemand_unique_together'),
        ('staff', '0007_staffprofile_religion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='role',
            field=models.CharField(choices=[('CLASS_TEACHER', 'Class Teacher'), ('SECOND_CLASS_TEACHER', 'Second Class Teacher'), ('SUBJECT_TEACHER', 'Subject Teacher')], default='SUBJECT_TEACHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='timetable.subject'),
        ),
    ]
