# Generated by Django 4.2.29 on 2026-07-21 17:44

from django.db import migrations

def migrate_roles(apps, schema_editor):
    TeacherAssignment = apps.get_model('staff', 'TeacherAssignment')
    
    # Update all existing to SUBJECT_TEACHER (just in case they aren't already)
    TeacherAssignment.objects.all().update(role='SUBJECT_TEACHER')
    
    # Find unique combinations of staff + class_section + academic_year where is_class_teacher was True
    class_teachers = TeacherAssignment.objects.filter(is_class_teacher=True).values(
        'staff_id', 'class_section_id', 'academic_year_id', 'tenant_id'
    ).distinct()
    
    # Create new CLASS_TEACHER assignments
    new_assignments = []
    import uuid
    for ct in class_teachers:
        new_assignments.append(
            TeacherAssignment(
                id=uuid.uuid4(),
                staff_id=ct['staff_id'],
                class_section_id=ct['class_section_id'],
                academic_year_id=ct['academic_year_id'],
                tenant_id=ct['tenant_id'],
                role='CLASS_TEACHER',
                subject=None,
                is_class_teacher=True # Keep it True for now before we drop it
            )
        )
    
    if new_assignments:
        TeacherAssignment.objects.bulk_create(new_assignments)

class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_teacherassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_code=migrations.RunPython.noop),
    ]
