# Generated by Django 4.2.29 on 2026-07-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_migrate_class_teacher_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherassignment',
            name='is_class_teacher',
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'SUBJECT_TEACHER')), fields=('staff', 'class_section', 'subject', 'academic_year'), name='unique_subject_teacher_per_section'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'CLASS_TEACHER')), fields=('class_section', 'academic_year'), name='unique_class_teacher_per_section'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'SECOND_CLASS_TEACHER')), fields=('class_section', 'academic_year'), name='unique_second_class_teacher_per_section'),
        ),
    ]
