# Generated by Django 4.2.29 on 2026-07-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_populate_academic_subjects'),
        ('staff', '0010_remove_teacherassignment_is_class_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.academicsubject'),
        ),
    ]
