# Generated by Django 4.2.29 on 2026-07-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_teacherassignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
