# Generated by Django 4.2.29 on 2026-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_individual_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='For INDIVIDUAL audience: active user email within the tenant.', max_length=254, null=True),
        ),
    ]
