# Generated by Django 4.2.29 on 2026-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0002_alter_documenttemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='type',
            field=models.CharField(choices=[('ID_CARD', 'ID Card'), ('FEE_RECEIPT', 'Fee Receipt'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('HALL_TICKET', 'Hall Ticket'), ('REPORT_CARD', 'Report Card (per student)'), ('REPORT_CARD_SUMMARY', 'Report Card Summary (section)')], max_length=50),
        ),
    ]
